### ISSUE TITLE
compilation erroe

### ISSUE THREAD

**Issue by maryamfatehifar** [Venky-94/sclsVofFoam-OpenFoam9#1]
Hello, first, thank you for sharing your work!

My first question is that I tried Menon et al. work, and it seems to me that the solver is not using the wall contact angle. Changing the contact angle in 0/alpha.water is not being recognized in their solver. Could you please let me know if you have any experience in that regard?

Second, I tried to use your code but received the error below. Could you help me solve the issue? Many thanks!

make
wmakeLnIncludeAll: running wmakeLnInclude on dependent libraries:
    wmakeLnInclude error: base directory /home/maryam-fatehifar/OpenFOAM/maryam-fatehifar-9/applications/solvers/multiphase/interFoamMod/twoPhaseModels/usertwoPhaseMixture/ does not exist
    wmakeLnInclude error: base directory /home/maryam-fatehifar/OpenFOAM/maryam-fatehifar-9/applications/solvers/multiphase/interFoamMod/twoPhaseModels/userinterfaceProperties/ does not exist
    wmakeLnInclude error: base directory /home/maryam-fatehifar/OpenFOAM/maryam-fatehifar-9/applications/solvers/multiphase/interFoamMod/twoPhaseModels/userincompressibleTwoPhaseMixture/ does not exist
    wmakeLnInclude error: base directory /home/maryam-fatehifar/OpenFOAM/maryam-fatehifar-9/applications/solvers/multiphase/interFoamMod/twoPhaseModels/userimmiscibleIncompressibleTwoPhaseMixture/ does not exist
    wmakeLnInclude error: base directory /home/maryam-fatehifar/OpenFOAM/maryam-fatehifar-9/applications/solvers/multiphase/interFoamMod/twoPhaseModels/usertwoPhaseChange/ does not exist
    wmakeLnInclude error: base directory /home/maryam-fatehifar/OpenFOAM/maryam-fatehifar-9/applications/solvers/multiphase/interFoamMod/twoPhaseModels/usertwoPhaseProperties/ does not exist
Making dependency list for source file sclsVofFoam.C
could not open file userimmiscibleIncompressibleTwoPhaseMixture.H for source file sclsVofFoam.C due to No such file or directory
could not open file usernoPhaseChange.H for source file sclsVofFoam.C due to No such file or directory
could not open file createAlphaFluxes.H for source file sclsVofFoam.C due to No such file or directory
could not open file setRDeltaT.H for source file sclsVofFoam.C due to No such file or directory
could not open file alphaCourantNo.H for source file sclsVofFoam.C due to No such file or directory
could not open file alphaControls.H for source file sclsVofFoam.C due to No such file or directory
could not open file alphaEqnSubCycle.H for source file sclsVofFoam.C due to No such file or directory
g++ -std=c++14 -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -Wno-attributes -O3  -DNoRepository -ftemplate-depth-100 -I/opt/openfoam9/src/transportModels/lnInclude -I/home/maryam-fatehifar/OpenFOAM/maryam-fatehifar-9/applications/solvers/multiphase/interFoamMod/twoPhaseModels/usertwoPhaseMixture/lnInclude -I/home/maryam-fatehifar/OpenFOAM/maryam-fatehifar-9/applications/solvers/multiphase/interFoamMod/twoPhaseModels/userinterfaceProperties/lnInclude -I/home/maryam-fatehifar/OpenFOAM/maryam-fatehifar-9/applications/solvers/multiphase/interFoamMod/twoPhaseModels/userincompressibleTwoPhaseMixture/lnInclude -I/home/maryam-fatehifar/OpenFOAM/maryam-fatehifar-9/applications/solvers/multiphase/interFoamMod/twoPhaseModels/userimmiscibleIncompressibleTwoPhaseMixture/lnInclude -I/home/maryam-fatehifar/OpenFOAM/maryam-fatehifar-9/applications/solvers/multiphase/interFoamMod/twoPhaseModels/usertwoPhaseChange/lnInclude -I/home/maryam-fatehifar/OpenFOAM/maryam-fatehifar-9/applications/solvers/multiphase/interFoamMod/twoPhaseModels/usertwoPhaseProperties/lnInclude -I/opt/openfoam9/src/MomentumTransportModels/momentumTransportModels/lnInclude -I/opt/openfoam9/src/MomentumTransportModels/incompressible/lnInclude -I/opt/openfoam9/src/finiteVolume/lnInclude -I/opt/openfoam9/src/dynamicFvMesh/lnInclude -I/opt/openfoam9/src/meshTools/lnInclude -I/opt/openfoam9/src/sampling/lnInclude -IlnInclude -I. -I/opt/openfoam9/src/OpenFOAM/lnInclude -I/opt/openfoam9/src/OSspecific/POSIX/lnInclude   -fPIC -c sclsVofFoam.C -o Make/linux64GccDPInt32Opt/sclsVofFoam.o
sclsVofFoam.C:42:10: fatal error: userimmiscibleIncompressibleTwoPhaseMixture.H: No such file or directory
   42 | #include "userimmiscibleIncompressibleTwoPhaseMixture.H"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [/opt/openfoam9/wmake/rules/General/transform:26: Make/linux64GccDPInt32Opt/sclsVofFoam.o] Error 1

**Comment by GuillaumeBroggi** [comment]
Hi!

Did you manage to solve this issue?

**Comment by Venky-94** [comment]
Hi @maryamfatehifar @GuillaumeBroggi, I haven't been working on OpenFoam for a while and moved to other things and wasn't able to get to this until now. Sorry about it.

For this error, please refer to the README I included in the main page of this solver. You will need to compile the twoPhaseModels library from the other solver I've posted first in order to use this level set solver as it is. (https://github.com/Venky-94/interFoamMod)

Alternatively you could swap the user libraries to OpenFoam's default libraries in the Make/options file of sclsVofFoam solver and compile it without compiling the user libraries. The difference between the user libraries and the default libraries is explained in the README of the interFoamMod solver.
(https://github.com/Venky-94/interFoamMod/blob/main/README.md)

Please let me know if you have any questions regarding this and I'll try to answer it as best possible :)
